baseURL = "http://forge-blog.netlify.com/"
languageCode = "en-us"
title = "Forge The Path"
enableRobotsTXT = true

[author]
  name = "Forge"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "JSON", "RSS" ]
  page = ["HTML" ]

[menu]
  [[menu.main]]
  identifier = "Summary"
  name       = "Summary"
  url        = "/summary/"
  weight     = 0
  
  [[menu.main]]
  identifier = "Articles"
  name       = "Articles"
  url        = "/"
  weight     = 1

SectionPagesMenu = "main"
paginate = 5
